### ISSUE TITLE
'Open Jitsi' button opens nothing (No 'Access-Control-Allow-Origin' header )

### ISSUE THREAD

**Issue by gray380** [d3473r/jitsi-keycloak#58] opened 2022-08-24 11:01 UTC
Hi,

Jitsi-web redirects to keycloak and jitsi-keycloak page opens after successful  authorization, but nothing happens when click on the 'open jitsi' button.

Could you help to find out the problem?

Regards
Serhiy.

**Comment by gray380** [comment] 2022-08-24 13:25
To be more specific, I have 

jitsi-web: https://jitsi.example.com
jitsi-keycloak: https://auth-jitsi.example.com 

JITSI ENV:
```
ENABLE_AUTH=1
AUTH_TYPE=jwt
JWT_APP_ID=jitsi
JWT_APP_SECRET=supersecret
TOKEN_AUTH_URL=https://auth-jitsi.example.com
```

JITSI KEYCLOAK ENV:
```
JITSI_SECRET=supersecret
DEFAULT_ROOM=meeting
JITSI_URL=https://jitsi.example.com
JITSI_SUB=example.com
```

And at the end `Open Jitsi` button directs to the `https://auth-jitsi.example.com/meeting`

**Comment by gray380** [comment] 2022-08-26 06:46
Seems that `jitsi-keycloak` can not get token from the `keycloak`;
```
Access to XMLHttpRequest at 'https://keycloak.test.lan/auth/realms/jitsi/protocol/openid-connect/auth?client_id=jitsi&state=841d9353-4895-4f23-80fc-61d23908c9f6&redirect_uri=http%3A%2F%2Fauth-jitsi.test.lan%2Fapi%2Fconfig%3Fauth_callback%3D1&scope=openid&response_type=code' (redirected from 'https://auth-jitsi.test.lan/api/config') from origin 'https://auth-jitsi.bank.lan' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

xhr.js:187          GET https://keycloak.test.lan/auth/realms/jitsi/protocol/openid-connect/auth?client_id=jitsi&state=841d9353-4895-4f23-80fc-61d23908c9f6&redirect_uri=http%3A%2F%2Fauth-jitsi.test.lan%2Fapi%2Fconfig%3Fauth_callback%3D1&scope=openid&response_type=code net::ERR_FAILED
```

**Comment by gray380** [comment] 2022-08-26 08:47
If replace correct Web Origins URI with "*"  (keycloak client's configuration) then no more 'Access-Control-Allow-Origin', but the following error has appear:
```
keycloak.js:790          POST https://keycloak.test.lan/auth/realms/jitsi/protocol/openid-connect/token net::ERR_FAILED 200
```

**Comment by gray380** [comment] 2022-08-26 15:33
Pay attention to this `rect_uri=http%3A%2F%2Fauth-jitsi.test`
`http` instead of `https`

**Comment by d3473r** [comment] 2022-08-26 16:25
Hi, do you have `https://auth-jitsi.bank.lan` in the Web Origins of keycloak?
This is the origin of the request

**Comment by gray380** [comment] 2022-08-29 06:08
Hi, yes I do.
I've tried with `https://auth-jitsi.bank.lan` with `*` and `+`.

Actions log:
login to the Keycloak
```
Access to XMLHttpRequest at 'https://keycloakdmz.test.lan/auth/realms/jitsi/protocol/openid-connect/auth?client_id=jitsi&state=bf3d4fd0-363b-47d3-a388-80d974e95c1b&redirect_uri=http%3A%2F%2Fauth-jitsi.test.lan%2Fapi%2Fconfig%3Fauth_callback%3D1&scope=openid&response_type=code' (redirected from 'https://auth-jitsi.test.lan/api/config') from origin 'https://auth-jitsi.test.lan' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Click 'OPEN JITSI'
```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of null (reading 'token')
    at a.openJitsi (App.vue:71:68)
    at re (vue.runtime.esm.js:1863:26)
    at a.n (vue.runtime.esm.js:2188:14)
    at re (vue.runtime.esm.js:1863:26)
    at Ln.t.$emit (vue.runtime.esm.js:3903:9)
    at a.click (VBtn.ts:163:7)
    at re (vue.runtime.esm.js:1863:26)
    at HTMLButtonElement.n (vue.runtime.esm.js:2188:14)
    at Qi.o._wrapper (vue.runtime.esm.js:6961:25)
   ``` 
jetsy-keycloak logout
keycloak login

token: 200
```
Response Headers
access-control-allow-credentials: true
access-control-allow-origin: https://auth-jitsi.test.lan
access-control-expose-headers: Access-Control-Allow-Methods
```
auth?client_id=... CORS error
```
General
Request URL: https://keycloakdmz.test.lan/auth/realms/jitsi/protocol/openid-connect/auth?client_id=jitsi&state=7bd22c6b-e428-4d1a-9d2f-76a6dbe76b8e&redirect_uri=http%3A%2F%2Fauth-jitsi.test.lan%2Fapi%2Fconfig%3Fauth_callback%3D1&scope=openid&response_type=code
Referrer Policy: strict-origin-when-cross-origin

Request Headers
Referer: https://auth-jitsi.test.lan/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.54
```
![image](https://user-images.githubusercontent.com/36230373/187133172-ac3028cf-2ae4-4544-8b78-bca164dadd86.png)

**Comment by gray380** [comment] 2022-08-30 17:28
BTW, if I set wrong  `Web Origins` it stops at the `token` stage:
![image](https://user-images.githubusercontent.com/36230373/187503611-7e6a7f40-250e-4100-9369-7372185f07e5.png)

with correct settings it stops `auth?client_id`

I've tried the following keycloak versions: 16.1.1, 19.0.1 (in the docker env)

**Comment by gray380** [comment] 2022-08-30 17:42
And if I try to put value of `access_token` or `id_token` to the url: 
`https://jitsi.test/lan/{room}?jwt={value of token}`

prosody says% `Error verifying token err:not-allowed, reason:Invalid signature`

![image](https://user-images.githubusercontent.com/36230373/187506587-b25959d5-5037-4607-a7ca-b05d7be05687.png)

**Comment by gray380** [comment] 2022-09-01 06:54
BTW
![image](https://user-images.githubusercontent.com/36230373/187850183-ea0c82e5-391c-4185-a3de-674faf33603e.png)

points to `config`
![image](https://user-images.githubusercontent.com/36230373/187850508-bbfb9aeb-64f1-4225-919b-5eeb05a65026.png)

```
        <div id="kc-error-message">
            <p class="instruction">Invalid parameter: redirect_uri</p>
        </div>
```

**Comment by d3hof** [comment] 2022-11-22 08:56
> Update: Keycloak (16 --> 19) changes `auth/realms/{realm}/protocol/openid-connect/token` to `realms/{realm}/protocol/openid-connect/token`.

You can go back to the old schema by adding to your KC environment `KC_HTTP_RELATIVE_PATH: "/auth"`

**Comment by imedia3** [comment] 2022-11-24 02:04
I have Exactly the same problem, 
May we have an update of this nice app instead of breaking all other Keycloak Clients by going back to old schema?

![image](https://user-images.githubusercontent.com/4366249/203675933-5f346837-1ff4-4f8c-afa1-c556b44b6b31.png)

**Comment by imedia3** [comment] 2022-11-25 10:54
> > Update: Keycloak (16 --> 19) changes `auth/realms/{realm}/protocol/openid-connect/token` to `realms/{realm}/protocol/openid-connect/token`.
> 
> You can go back to the old schema by adding to your KC environment `KC_HTTP_RELATIVE_PATH: "/auth"`

BTW, this setting broke KC container running at all

**Comment by d3473r** [comment] 2022-11-25 11:11
Hi all, I'll add a parameter to switch between the old and new keycloak configuration

**Comment by d3473r** [comment] 2022-11-25 11:29
Ehm, this configuration is coming from the keycloak adapter config `auth-server-url`.
Do you have downloaded the new adaptor config after the keycloak update?
For me its < 19: `"auth-server-url": "https://auth.example.com/auth/"`
and > 19: `"auth-server-url": "https://auth.example.com/",`

**Comment by imedia3** [comment] 2022-11-25 15:43
Hi, we have 4 other apps (2 via with SAML & 2 via with OpenID) which works well with our Keycloak 19 & 20.
They all working without "/auth" ending

**Comment by d3473r** [comment] 2022-11-25 17:16
Maybe your other apps autoconfigure via `.well-known/openid-configuration` which is more sophisticated
But this app requires a [Keycloak adapter configuration](https://www.keycloak.org/docs/latest/securing_apps/#keycloak-adapter-configuration) json file

**Comment by d3473r** [comment] 2022-11-25 20:35
I've update the keycloak-js adapter to the latest version (20.0.1).
Can you try again with `ghcr.io/d3473r/jitsi-keycloak:develop`?

**Comment by imedia3** [comment] 2022-11-25 21:11
I'm getting this error logs when trying to start it:

```
(node:1) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/app/src/app.js:9
import * as dotenv from 'dotenv'
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
(node:1) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/app/src/app.js:9
import * as dotenv from 'dotenv'
^^^^^^
```

**Comment by d3473r** [comment] 2022-11-26 08:59
Whoops, did an ES6 import, you can try again now :)

**Comment by imedia3** [comment] 2022-11-26 15:17
Unfortunately, same behaviour with the new image

This is console output after I got redirected with successful login:
![image](https://user-images.githubusercontent.com/4366249/204095573-562adf53-0cfa-4081-9804-875accaffbdf.png)

  This one is after I entered room name and clicked "Open Jitsi"
  
![image](https://user-images.githubusercontent.com/4366249/204095792-bac7861d-ab9d-4408-ab82-2e3ee4e71918.png)

**Comment by d3473r** [comment] 2022-11-27 15:03
Ok, did you you add `https://auth.meet.example.com` to the `Web origins` in the jitsi client in keycloak?

**Comment by imedia3** [comment] 2022-11-27 17:04
Hi, last mentioned problem was solved after I've recreated my client with same settings as before, but without any customization in attributes/roles, seems the problem was somewhere in token (I've tried some other ways to achieve KC auth in Jitsi before found your app).

Now I can successfully log in with any realm user account, but I still have one question: 
why I can't join to recently created rooms with member inside it: 

To reproduce:
1. Login with Account1, create room "test" and stay there, 
2. In another browser (also in incognito) open the same room with url `jitsi.domain/test` - here I can click "Join meeting" then I don't get redirection to Keycloak page for authorization, but receive a connection error with these errors in console (without 
![image](https://user-images.githubusercontent.com/4366249/204148389-3f423609-f0e1-4779-99ee-ddd3eb8b953a.png)
3. If Account1 leave the room, then Account2 can join and get Moderator privileges, then Account1 can enter back to the room with the same Moderator privileges
4. Is it possible in this solution to login once from any page you enter in Jitsi (even without any room), and then join any rooms without re-authorization?

I have 
ENABLE_AUTH=1
ENABLE_GUESTS=1

**Comment by d3473r** [comment] 2022-11-28 20:12
Awesome :)

Try adding `JWT_ENABLE_DOMAIN_VERIFICATION=false` in your config. See: https://github.com/jitsi/docker-jitsi-meet/issues/1369

I'm not sure what we have to set in the JWT to get this working without disabling the domain verification.

**Comment by imedia3** [comment] 2022-11-28 23:17
Now we are running 'stable-7648-3', but I prepare things to migrate to the latest

**Comment by d3473r** [comment] 2022-11-30 18:16
Maybe you are hitting this resgression: https://github.com/jitsi/jitsi-meet/issues/11967, https://github.com/jitsi/docker-jitsi-meet/issues/1369. 
This is fixed in the latest version via: https://github.com/jitsi/docker-jitsi-meet/pull/1396

**Comment by d3473r** [comment] 2022-12-01 13:00
@imedia3 i had to add `JWT_ALLOW_EMPTY=true` to the config. Otherwise a guest joining a existing room would get: `A conference with the same name has already been created!`

**Comment by s-sorokaty** [comment] 2023-02-17 05:07
> BTW ![image](https://user-images.githubusercontent.com/36230373/187850183-ea0c82e5-391c-4185-a3de-674faf33603e.png)
> 
> points to `config` ![image](https://user-images.githubusercontent.com/36230373/187850508-bbfb9aeb-64f1-4225-919b-5eeb05a65026.png)
> 
> ```
>         <div id="kc-error-message">
>             <p class="instruction">Invalid parameter: redirect_uri</p>
>         </div>
> ```
> 
> Update: Keycloak (16 --> 19) changes `auth/realms/{realm}/protocol/openid-connect/token` to `realms/{realm}/protocol/openid-connect/token`.

I have the same problem, do you solve problem with https -> http redirecting?

**Closed** 2023-03-27 16:36 UTC
