### ISSUE TITLE
Key ID(kid) missing

### ISSUE THREAD

**Issue by deridiot** [d3473r/jitsi-keycloak#28] opened 2021-04-20 13:10 UTC
With a commit from last month jitsi requires the kid parameter to be set which is currently not sent:
https://github.com/jitsi/jitsi-meet/commit/3a8bd852b277788925bba5f184e59e605f239cf3

       const { kid } = header;
        // if Key ID is missing, we return the error immediately without further validations.

2021-04-20T13:09:17.594Z [features/base/conference] JWT parsing error: 
Array [ "- Key ID(kid) missing" ]
Logger.js:154:22
2021-04-20T13:09:17.614Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: connection.passwordRequired Script: null Line: null Column: null StackTrace:  n/a Logger.js:154:22
Uncaught (in promise) connection.passwordRequired

**Comment by d3473r** [comment] 2021-05-04 21:41
Hi,

i think this is an issue with the PR you mentioned. This project uses a shared secret to sign the JWT.
From the jitsi [docs](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#token-structure):

> Alternately the token may be signed by a private key and authorized via public keyserver using RS256 tokens. In this mode, the 'kid' header of the JWT must be set to the name of the public key. The backend server must be configured to fetch and confirm keys from a pre-configured public keyserver.

So the `kid` parameter is only required (and makes sense) if the JWT was signed using a private key. Then the `kid` param would point to the public key which will be used by prosody to verify the signature.
I will open an issue on the jitsi repo to clarify this issue, thanks for the report 👍

**Comment by d3473r** [comment] 2021-05-05 14:38
The `kid` warning was fixed in jitsi with https://github.com/jitsi/jitsi-meet/pull/9146.
However the author mentioned that the `kid` error is not breaking, it did not prevent the auth flow.
So the error might be caused by an actual issue in JWT.
Test it with the current jitsi version and open a new issue if the error still persists.

**Closed by d3473r** 2021-05-05 14:38 UTC
